server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_template?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: lml

config:
  jwt:
#    加密密钥
    secret: iwqjhda8232bjgh432[cicada-smile]
#    有效时长
    expire: 3600
#    header名称
    header: token

yaml:
  str: 字符串可以不加引号
  specialStr: "双引号直接输出\n特殊字符"
  specialStr2: '单引号可以转义\n特殊字符'
  flag: false
  num: 666
  Dnum: 88.88

  pageSize: 10
  # 密钥
  secret: ioasdu9*(Hh9asdh898(HS(Dh9hasd9h
  list:
  - one
  - two
  - two
  set: [1,2,2,3]
  map: {k1: v1, k2: v2}
#  positions:
#  - name: ITDragon
#    salary: 15000.00
#  - name: ITDragonBlog
#    salary: 18888.88


mybatis:
  mapper-locations: classpath*:com.template.lml.demo.repository/*Mapper.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
#  supportMethodsArguments: true
  pageSizeZero: true
#  params: count=countSql
